name: Create Scratch Org
description: 'Execute a named Cumulus flow to create a scratch org'
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sfdx-version:
    description: 'version of SFDX to install'
    required: false
  dev-hub-auth-url:
    description: 'SFDX auth URL for the Dev Hub'
    required: true
  org-name:
    description: 'Name of the scratch org or persistent org config to use'
    required: true
  flow-name:
    description: 'Name of the Cumulus flow to execute'
    required: true
  commit-status-name:
    description: 'Name of an optional extra commit status to set from build results'
    required: true
    default: Scratch Org
runs:
    using: "composite"
    steps:
      - uses: actions/checkout@v3
      - name: Set Up CumulusCI
        uses: cumulus-actions/setup-cumulus@v1
        with:
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
      - name: Authenticate to Dev Hub
        uses: cumulus-actions/authorize-org@v1
        with:
          auth-url: '${{ inputs.dev-hub-auth-url }}'
          org-name: dev-hub
          dev-hub: true
      - name: Run Flow
        uses: cumulus-actions/run-flow@v1
        with:
          org-name: '${{ inputs.org-name }}'
          flow-name: '${{ inputs.flow-name }}'
      - name: Output Login URL
        run: |
          LOGIN_URL=$(cci org browser -r '${{ inputs.org-name }}' | tail -n 1)
          echo "Log into ${{ inputs.org-name }} at $LOGIN_URL"
        shell: bash
      - name: Set Commit Status
        if: '${{ inputs.commit-status-name }}'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state='success' \
            -f target_url="$LOGIN_URL" \
            -f context='${{ inputs.commit-status-name }}'
        shell: bash
      - name: Delete Scratch Org on Failure
        if: ${{ failure() }}
        run: |
          cci org scratch_delete '${{ inputs.org-name }}'
        shell: bash
